repos:

- repo: local
  hooks:
  - id: pip-compile-model
    name: compile requirements.txt
    entry: pip-compile requirements.in -o requirements.txt
    language: system
    always_run: false
    files: setup.py
    stages: [push]
